# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
name: lc_regression

channels:
  - conda-forge

dependencies:
  - python=3.8.0
  - nb_conda_kernels
  - pip
  - sncosmo==2.0.0

  - pip:
      - tqdm==4.32.1
      - numpy==1.16.4
      - scipy==1.2.1
      - sndata>=0.8.1
      - astropy==3.1.2
      - george==0.3.1
      - matplotlib
      - iminuit
